name: Userspace Build
on: [push, workflow_dispatch]

jobs:
  build:
    name: Userspace build
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        file:
        - blackflat.json
        - blackbowl.json
        - hypernano.json

    steps:
    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      uses: actions/checkout@v3.3.0
      with:
        repository: qmk/qmk_firmware
        ref: develop
        submodules: true

    - name: Checkout userspace
      uses: actions/checkout@v3.3.0
      with:
        path: users/${{ github.actor }}
        persist-credentials: false

    - name: Build
      continue-on-error: true
      working-directory: users/${{ github.actor }}/keymaps
      run: qmk -v compile -j 3 ${{ matrix.file }}

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        retention-days: 60
        name: ${{ matrix.file }}_${{ github.actor }}
        path: |
          *.hex
          *.bin
          *.uf2

